# Generated by Django 4.2.26 on 2025-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
